//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        public int IdArt { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> PreIni { get; set; }
        public Nullable<decimal> PreOfre { get; set; }
        public byte[] Imagen { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
